services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./php
    restart: always
    ports:
      - "80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: Senha123
      DB_NAME: meubanco
    depends_on:
      - db
  proxy:
    build: ./proxy
    restart: always
    ports:
      - "4500:4500"
    depends_on:
      - backend